import type { Metadata } from 'next'
import { Lexend } from 'next/font/google'
import './globals.css'
import Header from '../components/Header'
import { StoreProvider } from '../store/StoreProvider'

const lexend = Lexend({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lauris M',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang='en'>
        <body className={lexend.className}>
          <Header />
          <div className='relative'>{children}</div>
        </body>
      </html>
    </StoreProvider>
  )
}
