# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run unit tests

on:
  pull_request:
    branches: ['master', 'develop']

jobs:
  test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout application
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install packages
        run: npm install
      - name: Run unit tests
        run: npm test
